Feature/docker image check
planetarium/9c-k8s-config pull request #102
Opened 2022-11-15 06:19 UTC by sky1045

Add docker image check scripts
- DockerClient added
- fix some functions for prepare to reuse `get_latest_commit`

2022-11-15 06:42 UTC, Atralupus requested changes

2022-11-15 06:42 UTC, Atralupus commented on .github/workflows/prepare-release.yaml
> +          python cli.py check headless-image ${{ github.event.inputs.network }} ${{ github.event.inputs.rc }}
```suggestion
          python cli.py check headless-image ${{ github.event.inputs.network }} ${{ github.event.inputs.rc-number }}-${{ github.event.inputs.deploy-number }}
```

2022-11-15 06:42 UTC, Atralupus commented on py-scripts/toolbelt/prepare/repos.py
> +            continue
```suggestion
            raise ValueError("Not in valid repos")
```

2022-11-15 06:42 UTC, Atralupus commented on py-scripts/toolbelt/client/docker.py
> +        self._token = ""
I recommend to use `BaseUrlSession` [FYI](https://github.com/planetarium/9c-k8s-config/blob/cd1eef74235eef19e0b41fea6d6a8ab6d0393c1f/py-scripts/toolbelt/client/github.py#L23)

2022-11-15 06:42 UTC, Atralupus commented on py-scripts/toolbelt/client/docker.py
> +        self._username = username
In our case, no required auth for the docker hub rest API
```
 curl https://hub.docker.com/v2/namespaces/planetariumhq/repositories/ninechronicles-headless/tags/v100320
```

FYI https://docs.docker.com/docker-hub/api/latest/#tag/repositories/paths/~1v2~1namespaces~1%7Bnamespace%7D~1repositories~1%7Brepository%7D~1tags~1%7Btag%7D/get

2022-11-15 07:16 UTC, area363 approved these changes

2022-11-15 07:43 UTC, Atralupus commented on py-scripts/toolbelt/check/image.py
> +        branch = f"rc-v{rc}"
changed branch naming rule, now f"rc-v{rc}-{deploy_number}"
maybe we need a function for create rc branch

2022-11-15 07:43 UTC, Atralupus commented on py-scripts/toolbelt/prepare/repos.py
>      launcher_commit: Optional[str],
```suggestion
    launcher_commit: Optional[str] = None,
```

2022-11-15 07:43 UTC, Atralupus commented on py-scripts/toolbelt/prepare/repos.py
> +    player_commit: Optional[str]
```suggestion
    player_commit: Optional[str] = None
```

2022-11-15 07:43 UTC, Atralupus commented on py-scripts/toolbelt/client/docker.py
> +            f"{DOCKER_HUB_URL}/v2/namespaces/{self._namespace}/repositories/{repo}/tags/{tag}"
this request going to be not working
pls add docker client test

2022-11-15 07:43 UTC, Atralupus commented on py-scripts/toolbelt/check/image.py
> +        launcher_commit="",
Now, this code is needless

2022-11-15 07:43 UTC, Atralupus commented on py-scripts/toolbelt/check/image.py
> +        docker_client.check_image_exists("ninechronicles-headless", f"git-{commit}")
we should check exists a tag for deploy mainnet

2022-11-15 09:07 UTC, sky1045 commented on py-scripts/toolbelt/check/image.py
> +        branch = f"rc-v{rc}"
there seems to be no branch with new naming rule on 9c-headless, right?
no way to test with new branch name unless we create new branch for just test

2022-11-16 07:40 UTC, Atralupus commented on py-scripts/tests/client/test_docker.py
> +    requests_mock.get(
pls, add mocked response

2022-11-16 07:40 UTC, Atralupus commented on py-scripts/tests/client/test_docker.py
> +DOCKER_HUB_URL = "https://hub.docker.com"
```suggestion

```

2022-11-16 07:40 UTC, Atralupus commented on py-scripts/toolbelt/prepare/prepare.py
> +        branch = f"test-rc-v{rc_number}-{deploy_number}"
recommend not changing var name because I had used this var before

2022-11-16 07:40 UTC, Atralupus commented on py-scripts/toolbelt/prepare/prepare.py
> +        )
```suggestion
    )
```

2022-11-16 07:40 UTC, Atralupus commented on py-scripts/toolbelt/prepare/prepare.py
> +        )
or run `sh ./scripts/format.sh`

2022-11-16 07:40 UTC, Atralupus commented on py-scripts/toolbelt/client/docker.py
> +            f"{DOCKER_HUB_URL}/v2/namespaces/{self._namespace}/repositories/{repo}/tags/{tag}"
```suggestion
            f"/v2/namespaces/{self._namespace}/repositories/{repo}/tags/{tag}"
```

2022-11-16 07:40 UTC, Atralupus commented on py-scripts/toolbelt/client/docker.py
> +        return resp.status_code == 200
In this case, recommend to use `resp.raise_for_status()` and return `resp.json()`

2022-11-16 08:24 UTC, sky1045 commented on py-scripts/toolbelt/prepare/prepare.py
> +        branch = f"test-rc-v{rc_number}-{deploy_number}"
got it. then i should rename all `branch` variables to `rc_branch` below this line

2022-11-16 08:56 UTC, Atralupus approved these changes
Thanks!

2022-11-16 08:56 UTC, Atralupus commented on py-scripts/toolbelt/client/docker.py
> +    def check_image_exists(self, repo: str, tag: str) -> bool:
```suggestion
    def check_image_exists(self, repo: str, tag: str) -> Any:
```
`import Any from typing` required

2022-11-16 08:56 UTC, Atralupus commented
and rebase pls

2022-11-16 09:09 UTC, Atralupus approved these changes

2022-11-16 09:13 UTC, merged